### ISSUE TITLE
I have facing issue while running ui

### ISSUE THREAD

**Issue by pravinkumarravi** [katanaml/sparrow-donut#2]
![image](https://github.com/katanaml/sparrow-donut/assets/30704490/ed7fc84b-531a-4995-9df2-a5ff4d5379f1)

`2024-05-02 05:49:08.206 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/user/app/main.py", line 187, in <module>
    view(Model())
  File "/home/user/app/main.py", line 64, in view
    Dashboard().view(Dashboard.Model())
  File "/home/user/app/views/dashboard.py", line 61, in view
    with st.container():
         ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 332, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/elements/layouts.py", line 74, in container
    return self.dg._block()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit_nested_layout/nest.py", line 22, in _nestable_block
    ancestor_block_types = list(dg._ancestor_block_types)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'function' object is not iterable`

**Comment by abaranovskis-redsamurai** [comment]
You should debug Dashboard.view code, see stack trace. Here same UI works: https://huggingface.co/spaces/katanaml-org/sparrow-ui
